### ISSUE TITLE
Release on OPAM

### ISSUE THREAD

**Issue by dhil** [dhil/ocaml-multicont#1]
This library should be packaged and released on ~https://github.com/ocaml-multicore/multicore-opam~ https://github.com/ocaml/opam-repository.

**Comment by kayceesrk** [comment]
You should release it directly to OPAM. Multicore opam will soon be retired. And we're already releasing multicore packages on OPAM. See domainslib on opam for example: https://opam.ocaml.org/packages/domainslib/domainslib.0.4.0/.

**Comment by dhil** [comment]
I will release this library on OPAM once OCaml 5.0 is closer to release as right now it is volatile and interfaces are subject to change.
