### ISSUE TITLE
OCaml 5.2 support

### ISSUE THREAD

**Issue by kit-ty-kate** [dhil/ocaml-multicont#6]
I'm opening this just to track the issue started in https://github.com/kayceesrk/delimcc_of_fxhandler/issues/1

According to @dra27 https://github.com/ocaml/ocaml/pull/12735 could be the culprit

**Comment by dhil** [comment]
Thanks! I will try to dig into it later this week.

**Comment by dhil** [comment]
After a quick glance, I think I may have identified the problem. This is mostly a note for myself:

Patch ocaml/ocaml#12735 changes the continuation into a pair (first stack segment, last stack segment) but https://github.com/dhil/ocaml-multicont/blob/master/lib/multicont_stubs.c#L39 returns a stack pointer (as a continuation).

The cloning operation needs to be changed accordingly.

**Comment by dhil** [comment]
Should be fixed by #7. Thanks again @kit-ty-kate.
